# -*- coding: utf-8 -*-
"""Global Retail Enterprise Sales & Profitability Cube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duHdIc5BylgZOoeEhfd19XyqU8rZDNJx

# **Data Entery**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

df.head()

df.columns.to_list()

df.shape

df.info()

df.dtypes

df.describe()

df.describe(include="object")

df.isnull().sum()

df.duplicated().sum()

"""# **Data Cleaning**

"""

df.columns.to_list()

cat_cols = ['Ship Mode' , 'Customer Name' , 'Segment', 'Country',
 'City', 'State' , 'Region' , 'Category',
 'Sub-Category' , 'Category',
 'Sub-Category']

for col in cat_cols:
    print(df[col].unique())
    print('+' * 40)

for col in cat_cols:
    df[col] = df[col].str.strip()
    df[col] = df[col].str.capitalize()

df.columns.to_list()

num_cols = ['Postal Code' , 'Sales',
 'Quantity',
 'Discount',
 'Profit' ]

for col in num_cols:
    print(df[col].unique())
    print('+' * 40)

for col in num_cols:
    df[col] = pd.to_numeric(df[col])

date_cols = ['Order Date' , 'Ship Date']

for col in date_cols :
  df[col] = pd.to_datetime(df[col] , errors='coerce')

df.dtypes

from google.colab import files

df.to_csv("cleaned_data.csv", index=False)
files.download("cleaned_data.csv")